---
- name: "{{ play_name }}"
  hosts: "{{ target_host }}"
  become: "{{ become_root }}" # Run commands with elevated privileges (e.g., sudo)
  vars_files:
    - variables/vars_app_deployment_config.yaml

  tasks:
    - name: Make the script executable
      shell: "{{ assign_execute_permission }}"

    - name: Execute the shell script
      shell: "{{ execute_automation_script }}"

